#!/bin/sh
# mk-bgfw.sh — emit the Gen 5 BG co-processor firmware blobs as C arrays.
#
# Both images live on the watch's own modem partition (FAT16, /image):
#   bgapp.mdt + bgapp.b00..b03    the SIGNED TrustZone app that loads the BG
#   bg-wear.mdt + bg-wear.b00..b02  the co-processor firmware itself
# QSEECOM/PIL want each image as ONE buffer: the .mdt followed by its .bNN
# blobs in order, with mdt_len = size of the .mdt alone. That is exactly what
# this script concatenates, so the C arrays can be handed to TZ as-is.
#
# Usage: sh tools/mk-bgfw.sh <modem.img> <outdir>
set -e
MODEM="$1"; OUT="$2"
[ -n "$MODEM" ] && [ -n "$OUT" ] || { echo "usage: mk-bgfw.sh <modem.img> <outdir>"; exit 1; }
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
mkdir -p "$OUT"

emit() {  # emit <name> <c_symbol> <nblobs>
  name="$1"; sym="$2"; n="$3"
  mcopy -o -i "$MODEM" "::/image/$name.mdt" "$TMP/$name.mdt"
  mdt_len=$(stat -c %s "$TMP/$name.mdt")
  cat "$TMP/$name.mdt" > "$TMP/$name.img"
  i=0
  while [ "$i" -lt "$n" ]; do
    b=$(printf 'b%02d' "$i")
    mcopy -o -i "$MODEM" "::/image/$name.$b" "$TMP/$name.$b"
    cat "$TMP/$name.$b" >> "$TMP/$name.img"
    i=$((i+1))
  done
  img_len=$(stat -c %s "$TMP/$name.img")
  echo "[bgfw] $name: mdt $mdt_len + $n blobs = $img_len bytes"
  # Per-blob offsets: blob i holds ELF program-header i's DATA. The .mdt is
  # segments 0+1 joined and the .bNN files do NOT sit at the ELF p_offset
  # values inside the concatenation, so a loader that walks program headers
  # needs this table rather than p_offset.
  offs=""; lens=""; pos=$mdt_len; i=0
  while [ "$i" -lt "$n" ]; do
    b=$(printf 'b%02d' "$i"); sz=$(stat -c %s "$TMP/$name.$b")
    offs="$offs $pos,"; lens="$lens $sz,"; pos=$((pos+sz)); i=$((i+1))
  done
  python3 - "$TMP/$name.img" "$sym" "$mdt_len" "$n" "$offs" "$lens" >> "$OUT/bg_fw.c" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read(); sym = sys.argv[2]; mdt = int(sys.argv[3])
n = int(sys.argv[4]); offs = sys.argv[5].split(); lens = sys.argv[6].split()
print("const unsigned int %s_mdt_len = %u;" % (sym, mdt))
print("const unsigned int %s_len = %u;" % (sym, len(data)))
print("const unsigned int %s_nblob = %u;" % (sym, n))
print("const unsigned int %s_blob_off[%u] = { %s };" % (sym, n, " ".join(offs)))
print("const unsigned int %s_blob_len[%u] = { %s };" % (sym, n, " ".join(lens)))
print("const unsigned char %s[%u] = {" % (sym, len(data)))
for i in range(0, len(data), 16):
    print("  " + "".join("0x%02x," % b for b in data[i:i+16]))
print("};")
PY
}

cat > "$OUT/bg_fw.c" <<'H'
/* bg_fw.c — GENERATED by tools/mk-bgfw.sh from the watch's modem partition.
 * Qualcomm/Fossil vendor firmware; not ours, not in git. Each array is a
 * .mdt followed by its .bNN blobs, the layout QSEECOM and PIL expect. */
H
emit bgapp   bgapp_img   4
emit bg-wear bg_wear_img 3
echo "[bgfw] wrote $OUT/bg_fw.c ($(stat -c %s "$OUT/bg_fw.c") bytes)"
