#!/bin/sh
# mk-wcnss-nv.sh — turn a watch's WCNSS NV blob + MAC into the wcnss_nv.c the
# bare-metal build embeds, so WiFi/BLE on the Wear 2100 watches use the
# radio calibration and MAC address that shipped with that exact unit.
#
# The two inputs live in the watch's `persist` partition:
#   /persist/WCNSS_qcom_wlan_nv.bin   ~31 KB radio NV table
#   /persist/wifimac.ini              12 hex digits, the unit's WiFi MAC
# Pull them from a root adb shell (TWRP RAM-booted with `fastboot boot`):
#   adb pull /persist/WCNSS_qcom_wlan_nv.bin
#   adb pull /persist/wifimac.ini
#
# Usage: sh snapdragon-port/tools/mk-wcnss-nv.sh <nv.bin> <wifimac.ini|MAC|none> <board>
#   board = gen4 | c2 | s2   (writes snapdragon-port/firmware/<board>/wcnss_nv.c)
# The output directory is gitignored on purpose: it contains YOUR MAC address.
#
# PASS `none` FOR ANY IMAGE YOU INTEND TO PUBLISH. A baked MAC ends up inside
# the .img, so a release built with one makes every watch that flashes it
# transmit YOUR address -- your identifier on strangers' networks, and an ARP/
# DHCP fight whenever two of them share a network. With `none` no wcnss_mac
# symbol is emitted and the firmware derives a locally-administered MAC per
# device from the eMMC CID instead (see wlan_mac() in platform/wcnss.c). The NV
# blob itself is board data, byte-identical across every unit we have compared,
# and carries no MAC -- that part is safe to ship.
set -e
NV="$1"; MACSRC="$2"; BOARD="$3"
[ -f "$NV" ] && [ -n "$MACSRC" ] && [ -n "$BOARD" ] || { sed -n 2,16p "$0"; exit 1; }
if [ "$MACSRC" = none ]; then MAC=none
elif [ -f "$MACSRC" ]; then MAC=$(tr -dc '0-9A-Fa-f' < "$MACSRC")
else MAC=$(printf %s "$MACSRC" | tr -dc '0-9A-Fa-f'); fi
[ "$MAC" = none ] || [ ${#MAC} -eq 12 ] || { echo "MAC must be 12 hex digits or 'none', got '$MAC'"; exit 1; }
OUT="$(dirname "$0")/../firmware/$BOARD/wcnss_nv.c"
mkdir -p "$(dirname "$OUT")"
python3 - "$NV" "$MAC" "$OUT" "$BOARD" <<'PY'
import sys
nv, mac, out, board = sys.argv[1:]
data = open(nv, 'rb').read()
nomac = (mac == 'none')
m = [] if nomac else [mac[i:i+2] for i in range(0, 12, 2)]
with open(out, 'w') as f:
    if nomac:
        f.write(f"/* GENERATED by snapdragon-port/tools/mk-wcnss-nv.sh from {nv} ({board}).\n"
                "   NO MAC baked in -- wlan_mac() derives one per device from the eMMC CID.\n"
                "   This is the form to build published release images with. */\n")
    else:
        f.write(f"/* GENERATED by snapdragon-port/tools/mk-wcnss-nv.sh from {nv} ({board}). Contains this unit's MAC -- not for commit, not for a release image. */\n")
    f.write("#include <stdint.h>\n")
    if not nomac:
        f.write("const uint8_t wcnss_mac[6] = { " + ", ".join("0x" + x for x in m) + " };\n")
    f.write(f"const uint32_t wcnss_nv_len = {len(data)};\n")
    f.write(f"const uint8_t wcnss_nv_bin[{len(data)}] __attribute__((aligned(4))) = {{\n")
    for i in range(0, len(data), 16):
        f.write("  " + ",".join("0x%02x" % b for b in data[i:i+16]) + ",\n")
    f.write("};\n")
print(f"wrote {out} ({len(data)} bytes, mac {'derived per device from the eMMC CID' if nomac else ':'.join(m)})")
PY
