#!/bin/sh
# mk-wcnss-nv.sh — turn a watch's WCNSS NV blob + MAC into the wcnss_nv.c the
# bare-metal build embeds, so WiFi/BLE on the Wear 2100 watches use the
# radio calibration and MAC address that shipped with that exact unit.
#
# The two inputs live in the watch's `persist` partition:
#   /persist/WCNSS_qcom_wlan_nv.bin   ~31 KB radio NV table
#   /persist/wifimac.ini              12 hex digits, the unit's WiFi MAC
# Pull them from a root adb shell (TWRP RAM-booted with `fastboot boot`):
#   adb pull /persist/WCNSS_qcom_wlan_nv.bin
#   adb pull /persist/wifimac.ini
#
# Usage: sh snapdragon-port/tools/mk-wcnss-nv.sh <nv.bin> <wifimac.ini|MAC> <board>
#   board = gen4 | c2 | s2   (writes snapdragon-port/firmware/<board>/wcnss_nv.c)
# The output directory is gitignored on purpose: it contains YOUR MAC address.
set -e
NV="$1"; MACSRC="$2"; BOARD="$3"
[ -f "$NV" ] && [ -n "$MACSRC" ] && [ -n "$BOARD" ] || { sed -n 2,16p "$0"; exit 1; }
if [ -f "$MACSRC" ]; then MAC=$(tr -dc '0-9A-Fa-f' < "$MACSRC"); else MAC=$(printf %s "$MACSRC" | tr -dc '0-9A-Fa-f'); fi
[ ${#MAC} -eq 12 ] || { echo "MAC must be 12 hex digits, got '$MAC'"; exit 1; }
OUT="$(dirname "$0")/../firmware/$BOARD/wcnss_nv.c"
mkdir -p "$(dirname "$OUT")"
python3 - "$NV" "$MAC" "$OUT" "$BOARD" <<'PY'
import sys
nv, mac, out, board = sys.argv[1:]
data = open(nv, 'rb').read()
m = [mac[i:i+2] for i in range(0, 12, 2)]
with open(out, 'w') as f:
    f.write(f"/* GENERATED by snapdragon-port/tools/mk-wcnss-nv.sh from {nv} ({board}). Contains this unit's MAC -- not for commit. */\n")
    f.write("#include <stdint.h>\n")
    f.write("const uint8_t wcnss_mac[6] = { " + ", ".join("0x" + x for x in m) + " };\n")
    f.write(f"const uint32_t wcnss_nv_len = {len(data)};\n")
    f.write(f"const uint8_t wcnss_nv_bin[{len(data)}] __attribute__((aligned(4))) = {{\n")
    for i in range(0, len(data), 16):
        f.write("  " + ",".join("0x%02x" % b for b in data[i:i+16]) + ",\n")
    f.write("};\n")
print(f"wrote {out} ({len(data)} bytes, mac {':'.join(m)})")
PY
